# Generated by Django 2.2.7 on 2020-12-29 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNo', models.BigIntegerField(unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(8)])),
                ('rpassword', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
